### ISSUE TITLE
bug in "public static void slide(byte[] r, byte[] a)"

### ISSUE THREAD

**Issue by bootshow** [langboost/curve25519-pcl#5]
i think must change to "public static void slide(**sbyte**[] r, byte[] a)"

**Comment by jeff-r-skillrev** [comment]
sbyte is just a signed version of byte. I'd prefer to use one data type consistently everywhere we can. I did deviate in the negative(sbyte ...) function, but only because a signed type was necessary for the algorithm to work when ported to C#. Everywhere else should be a byte data type.

**Comment by jeff-r-skillrev** [comment]
You were right. Using byte was breaking the comparison logic in the slide function. I couldn't compare to -15. This is fixed now. Thanks for your help!
